import os

SECRET_KEY = os.urandom(16)
ALGORITHM = "HS256"
ROOT_PATH = "/api/v1"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
REFRESH_TOKEN_EXPIRE_DAYS = 7

CELERY_BACKEND = "rpc://"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

IPDATA_URL = f'https://api.ipdata.co/'

from app.local_config import DB_USER, DB_PASSWORD, DB_HOST, DB_DATABASE, IPDATA_TOKEN, CELERY_BROKER
